### ISSUE TITLE
Yaml config override does not change the binding variables in the config file

### ISSUE THREAD

**Issue by eugene-yang** [hltcoe/patapsco#33]
For config files that use config variables for run name, the overriding variables are not considered when binding the variables. 
For example, when running `patapsco test_config.yml --set queries.psq.path=dummy.dict` and the config file is something like

```yaml
run:
    name: psq-{queries.psq.path}
....
queries:
    psq:
        path: original.dict
```

The run name will still be `psq-original.dict`. 

The variable checks also take place before the overriding variables are put into the config object. Ideally, it should be checked after processing the overriding variables. 
https://github.com/hltcoe/patapsco/blob/master/patapsco/config.py#L118
